language: java
jdk:
- openjdk8
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: Bo+1JP+njrfWS7XGhWwKN5CRLVpK5ynC8fCHWFy6lAyPwOiKELXAepFuR3KwrajrDzGQJesV8whT50JlyNnHqVuT7vku3y9dMmtvOJLM7b+N87wbtZlubPGVo6rlPaOqnMmzBr4OcjT27nhLNooREkgDERJSzBopxZWNuM/peNezRghFXmyoJlKmJJmhdZWnE5u9CJEcs6svAhfYJSjLqxZo5QtLOh4du5thbscGGOMrNtYq8bBEUJGIOV8ZzdNSK1qin9pR842oNnVF6EMjgkpbXXDOxf85KRI/0dNPhOzUEn0Z0VaiAym/dYrVo2GmJGw78cSxmfrb3fTIDDHQj4enBkQ0y01fzf/XuaUfx9mFDP67Z/ngmGixNPdXqEK+WtUQ1R9c+cfYGLDn/ve6RMOLPqWJe3a/lf7b3lTEWAVO+AdldN628+WPpQGxMlwFOuxY1c63v9ZwT5g7ZA4OQ0KJ6d18rpRhwx1m29qkR9z5+lhuQDaj55x81/IX5DY5dDiyinG3KtgLugSmRhgZfM76qvcm7fDh1EhpJgMiU+746gjH5n94Fg8dT88clbw7ApzQOMAYPRu35kugp2I6FIopnRnbizj4E8h5hUyCbNO7cG9EmVU4TDQ9kdCP6zs+rxKl44N7ZV/5T3Qew4ckW54fe0/aLd92cCxY/AMN1SY=
  - secure: "nBqyB+NXZdjRFlkcXCn5DD9n6vJUQJapXy1z/rkF6R9dlGJZqxuEGHgrrkRLxJ8rjsIA8rfOtE+eNfDIb1wMTZnfYWGnqAOfWUK7GkAcH41mt6V3IgnDHYsZFvTVA1UkIAf0BzhvBURJ/u02sRWvhXwlt54xdqjbQVTyzCvI9kHyuFiK6JInRtmsOylABhQ5CgcDiAwl8KUmncr1NTpW7PNuRBedRZQYIfzaSjV/7T/REzBAUAjL7YxxKQDdw9PbtIUlP1YUT2P5snYSJVeN/QB31Cy/POG8On40fWAFpiSD7C22iEETIkkZ/KQVyZuaZWw/Ymf7Xansi3zb/XBRHOpq50XxsYI9lN7svUfBIVp2soL+UXyolfAi2QNBj7Och6LHD1PzwjK84j2LKapyTfGC4HHvy3vas6dD/sVYRVMi2cnA2nr2QgtuXPKu778r/gCSAvn9PpxgrU7HOT671s6UjFp7EbUBRH1a+MIJOgl0j3Zbjf6g2yleF7nX2aOOXc2HnMM0Ur5VBWcrihIAvWXXxes465Rur2DZ5QpR/EQdkUwEH3XM+awc+MlcYHqFbrWIYgsGu79TrFMy1CjLhQ6Xa3nfZr52xMR7oxNzfag0vLzmGrBIV2kf0Npgm2LvxS96S/0i3xMXZjmoWXFHjRgEjiiMVmXkgN4FcpIkV1s="
script:
- mvn package dockerfile:push
