language: java
jdk:
- openjdk8
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: Bo+1JP+njrfWS7XGhWwKN5CRLVpK5ynC8fCHWFy6lAyPwOiKELXAepFuR3KwrajrDzGQJesV8whT50JlyNnHqVuT7vku3y9dMmtvOJLM7b+N87wbtZlubPGVo6rlPaOqnMmzBr4OcjT27nhLNooREkgDERJSzBopxZWNuM/peNezRghFXmyoJlKmJJmhdZWnE5u9CJEcs6svAhfYJSjLqxZo5QtLOh4du5thbscGGOMrNtYq8bBEUJGIOV8ZzdNSK1qin9pR842oNnVF6EMjgkpbXXDOxf85KRI/0dNPhOzUEn0Z0VaiAym/dYrVo2GmJGw78cSxmfrb3fTIDDHQj4enBkQ0y01fzf/XuaUfx9mFDP67Z/ngmGixNPdXqEK+WtUQ1R9c+cfYGLDn/ve6RMOLPqWJe3a/lf7b3lTEWAVO+AdldN628+WPpQGxMlwFOuxY1c63v9ZwT5g7ZA4OQ0KJ6d18rpRhwx1m29qkR9z5+lhuQDaj55x81/IX5DY5dDiyinG3KtgLugSmRhgZfM76qvcm7fDh1EhpJgMiU+746gjH5n94Fg8dT88clbw7ApzQOMAYPRu35kugp2I6FIopnRnbizj4E8h5hUyCbNO7cG9EmVU4TDQ9kdCP6zs+rxKl44N7ZV/5T3Qew4ckW54fe0/aLd92cCxY/AMN1SY=
  - secure: raB5szJ0h3USrj2tODbdxCaAEqEICUxcHxQ8sDCWKuCnriH8RpfHhURMyyX60P1VFzXJvnocjXMa7So79LCkYMCC4d8vrQ+RiEKdAtFJWntfLv6PY2G05B5oABA8HEXGSbYbNcZsqiKmlptAa8qcAHm4xVR8VP+tWY8ayOTcbUiTU1vpRjI97OYAcFJBAXqYTkLj85Or4ygZ9cZs8GyBY0zFpavBs9qkSxvK4uNlLYvXUxJ1rdUwU9v6zKCdHTYEJu+8v7mrUh6LPPALAxPJbfguavCS/Mmihe4IFrLdyuOWPc/N9fFCj0ZnJawXZTe0NwO6o1nh1p7rx2sx6zPdAL86BQAonEkhTLIWZo0Bgt+zLIkPlkok6A8GT5J5qZrxUTUi1Ugjgm+npDsp57Ujn/FquyoBOFJvAoR8QTcmeKWIBTw6RES4SOdloboy8Ak1boEpaPokdA3m+4rMbzOMZwRdTjzjawVPfM6BI0QqUvZlmkRgm5rwg5ybw+JKtscAPHbPoqIfROcwItKuzRE/NGXv1KnvlkPQ1Iocj4vn/1547BrnpS7LA+38Qv2uHm6Dm43j+YlrHgoPju5YXcg2b5oFTVOEcb85W0LMqvcToMXVdLmpBqo4u0+UKY6SRf0RuDvBBfU4ZP96xkCV+3apMvMGrIlk9sb0yuhfTXV2aLM=
script:
- mvn package dockerfile:push
